easy_admin:
    site_name: 'FireCMS'
   
    
    
    entities:
        
        Widgets:
          class: App\Entity\Widgets

        WidgetPositions:
          class: App\Entity\WidgetPositions
        
        Links:
          class: App\Entity\Routes

        Templates:
          class: App\Entity\Templates
          
        
        Dienstbuch:
            class: App\Entity\Dienstbuch
        
        User:
            class: App\Entity\User
        
        Members:
            class: App\Entity\Members
 
