admin:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index

app_dashboard:
    path: /admin/dashboard
    controller: App\Controller\Admin\DashboardController::index

app_users:
    path: /admin/users/overview
    controller: App\Controller\Admin\UserController::number


app_dienstbuch:
    path: /admin/dienstbuch/list/{id}
    controller: App\Controller\Admin\DienstbuchController::list

dienstbuch.neu:
    path: /admin/dienstbuch/neu
    controller: App\Controller\Admin\DienstbuchController::create

dienstbuch.list:
    path: /admin/dienstbuch/alle
    controller: App\Controller\Admin\DienstbuchController::list

mitglieder.list:
    path: /admin/listmembers
    controller: App\Controller\Admin\MemberController::list

mitglieder.create:
    path: /admin/createmembers
    controller: App\Controller\Admin\MemberController::create

app_register:
    path: /admin/register
    controller: App\Controller\Admin\RegistrationController::register

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\Admin\SecurityController::login

app_editmember:
    path: /editmember/{id}
    controller: App\Controller\Admin\MemberController::editmember

