# Admin Routes
Admin Login:
    path: /admin/login
    controller: App\Controller\SecurityController::login

Logout:
    path: /logout
    controller: App\Controller\Admin\SecurityController::login
Router:
    path: /router
    controller: App\Controller\AdminController::routeAction
Admin:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index

Dashboard:
    path: /admin/dashboard
    controller: App\Controller\Admin\DashboardController::index

Users:
    path: /admin/users/overview
    controller: App\Controller\Admin\UserController::number

Neues Dienstbuch:
    path: /admin/dienstbuch/neu
    controller: App\Controller\Admin\DienstbuchController::create

Alle Dienstbücher:
    path: /admin/dienstbuch/alle
    controller: App\Controller\Admin\DienstbuchController::list

Alle Mitglieder:
    path: /admin/listmembers
    controller: App\Controller\Admin\MemberController::list

Neues Mitglied:
    path: /admin/createmembers
    controller: App\Controller\Admin\MemberController::create

Registrieren:
    path: /admin/register
    controller: App\Controller\Admin\RegistrationController::register



app_editmember:
    path: /editmember/{id}
    controller: App\Controller\Admin\MemberController::editmember

